<a href="https://colab.research.google.com/github/IBM-EPBL/IBM-Project-774-1658321575/blob/main/G_L_HARIPRASANTH_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [ ]:
x=s.split()
print(x)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [ ]:
print('The diameter of {planet} is {diameter} kilometers.'.format(planet="Earth",diameter=12742));

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
ans=d['k1'][3]['tricky'][3]['target'][3]
print(ans)

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
array=np.zeros(10)
print('The array with 10 zeros:')
print(array)

The array with 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
array=np.ones(10)*5
print('The array with 10 fives:')
print(array)

The array with 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [ ]:
array=np.arange(20,35,2)
print('The array of all the even integer from 20 to 35:')
print(array)

The array of all the even integer from 20 to 35:
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
array=np.arange(0,9).reshape(3,3)
print('The matrix with values ranges from 0 to 8:')
print(array)

The matrix with values ranges from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
x=np.concatenate((a,b),axis=0)
print('The concatenation of two array a and b:')
print(x)

The concatenation of two array a and b:
[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [ ]:
data = [['hari', 10], ['karthi', 15], ['aswin', 14]]
df = pd.DataFrame(data,columns=['Name','Age'])
print('The dataframe with 3 rows and 2 columns:')
print(df)

The dataframe with 3 rows and 2 columns:
     Name  Age
0    hari   10
1  karthi   15
2   aswin   14


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
import datetime
test_date = datetime.datetime.strptime("01-01-2022", "%d-%m-%Y")
date_series = pd.date_range(test_date, periods=41)
print('The series of data from 1st jan,2023 to 10th feb,2023:')
print(date_series.strftime("%d-%m-%Y"))

The series of data from 1st jan,2023 to 10th feb,2023:
Index(['01-01-2022', '02-01-2022', '03-01-2022', '04-01-2022', '05-01-2022',
       '06-01-2022', '07-01-2022', '08-01-2022', '09-01-2022', '10-01-2022',
       '11-01-2022', '12-01-2022', '13-01-2022', '14-01-2022', '15-01-2022',
       '16-01-2022', '17-01-2022', '18-01-2022', '19-01-2022', '20-01-2022',
       '21-01-2022', '22-01-2022', '23-01-2022', '24-01-2022', '25-01-2022',
       '26-01-2022', '27-01-2022', '28-01-2022', '29-01-2022', '30-01-2022',
       '31-01-2022', '01-02-2022', '02-02-2022', '03-02-2022', '04-02-2022',
       '05-02-2022', '06-02-2022', '07-02-2022', '08-02-2022', '09-02-2022',
       '10-02-2022'],
      dtype='object')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
df = pd.DataFrame(lists,columns=['column1','column2','column3'])
print('The 2D list of dataframe:')
print(df)

The 2D list of dataframe:
   column1 column2  column3
0        1     aaa       22
1        2     bbb       25
2        3     ccc       24
